#! /bin/sh

#
# make sure all processes are killed
#

killall -q polybar
killall -q sxhkd
killall -q picom
killall -q bato

#
# something
#

pgrep -x sxhkd > /dev/null
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x bato >/dev/null; do sleep 1; done
# while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

#
# AUTOSTART
#

xrandr --output HDMI1 --mode 1920x1080 --right-of eDP1 &
xsetroot -cursor_name arrow &
sxhkd &
systemctl --user import-environment DISPLAY &
deadd-notification-center &
clipmenud &
bato &
/home/via/.config/bspwm/scripts/randomwallpaper &
bash ~/.config/polybar/launch.sh &
signal-desktop --start-in-tray --use-tray-icon --no-sandbox %U &
xrdb ~/.Xresources &
wmname LG3D &
picom &
xss-lock -l -- multilockscreen --lock &
eww daemon -c /home/via/.config/eww &
multilockscreen --update ~/Pictures/locks --fx dim &

#
# bspwm
# 

bspc monitor -d 1 2 3 4 5 

bspc config border_width        0
bspc config window_gap          5

bspc config normal_border_color  "#090909" # #02020E" #"#222d70" #C93357
bspc config focused_border_color "#090909"     #"#f288a2"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc rule -a '*' state=floating
bspc rule -a google-chrome state=tiled desktop="^2" follow=on
